### ISSUE TITLE
Could you share the sample data and codes used by the paper, please?

### ISSUE THREAD

**Issue by flippercy** [leiyu0210/TimeLangNet#1]
Hi @yahui-lee @leiyu0210 :

Could you share the sample data and codes used by your paper, please? I'd like to test the algorithm.

If the sample data is classified, could you upload a similar and public dataset to show the format needed?

Thank you.

**Comment by leiyu0210** [comment]
The data is already in the readme file suggesting that it is the "UEA" Dataset. https://www.timeseriesclassification.com/
